import os
import sqlite3
from flask import Flask, render_template_string, request, redirect, session, jsonify
import ccxt
from datetime import datetime

app = Flask(__name__)
app.secret_key = 'mag_unefa_cloud_v27'

# --- 1. BASE DE DATOS ---
def init_db():
    conn = sqlite3.connect('usuarios.db')
        conn.execute('CREATE TABLE IF NOT EXISTS users (username TEXT PRIMARY KEY, password TEXT)')
            conn.commit()
                conn.close()

                exchange = ccxt.binance() 
                MONEDAS = ['BTC/USDT', 'ETH/USDT', 'SOL/USDT', 'BNB/USDT']

                # --- 2. IA DE INVERSIÓN (Cada 10 segundos) ---
                def analizar_inversion():
                    rec = {}
                        for m in MONEDAS:
                                try:
                                            ohlcv = exchange.fetch_ohlcv(m, timeframe='1m', limit=2)
                                                        actual, previa = ohlcv[-1][4], ohlcv[-2][4]
                                                                    rec[m] = "🚀 COMPRAR" if actual > previa else "⏳ ESPERAR"
                                                                            except: rec[m] = "Analizando..."
                                                                                return rec

                                                                                # --- 3. TU GRÁFICA AZUL Y AMARILLA ---
                                                                                URL_GRAFICA = "https://i.imgur.com/8fM95G3.png"

                                                                                ESTILOS = f'''
                                                                                <style>
                                                                                    body {{ background: #000; margin: 0; font-family: sans-serif; color: white; overflow: hidden; }}
                                                                                        .mag-bg {{
                                                                                                position: fixed; top: 0; left: 0; width: 125%; height: 125%;
                                                                                                        background: url('{URL_GRAFICA}') no-repeat center center;
                                                                                                                background-size: cover; filter: brightness(0.25) contrast(1.2);
                                                                                                                        z-index: -1; animation: pan_mag 35s infinite alternate ease-in-out;
                                                                                                                            }}
                                                                                                                                @keyframes pan_mag {{ from {{ transform: translate(0,0); }} to {{ transform: translate(-4%, -4%); }} }}
                                                                                                                                    .card {{ 
                                                                                                                                            background: rgba(13, 17, 23, 0.95); backdrop-filter: blur(12px);
                                                                                                                                                    border: 1px solid #30363d; padding: 40px; border-radius: 20px; 
                                                                                                                                                            width: 320px; text-align: center; margin: 10vh auto;
                                                                                                                                                                }}
                                                                                                                                                                    input {{ width: 100%; padding: 12px; margin: 10px 0; border-radius: 8px; border: 1px solid #30363d; background: #0d1117; color: white; box-sizing: border-box; }}
                                                                                                                                                                        button {{ width: 100%; padding: 12px; background: #238636; border: none; color: white; font-weight: bold; border-radius: 8px; cursor: pointer; }}
                                                                                                                                                                        </style>
                                                                                                                                                                        '''

                                                                                                                                                                        LOGIN_HTML = f"<html><head>{ESTILOS}</head><body><div class='mag-bg'></div><div class='card'><h2>MAG PRO v27.5</h2><form action='/login' method='POST'><input name='u' placeholder='Usuario'><input name='p' type='password' placeholder='Clave'><button>ENTRAR</button></form></div></body></html>"

                                                                                                                                                                        DASH_HTML = '''
                                                                                                                                                                        <!DOCTYPE html>
                                                                                                                                                                        <html>
                                                                                                                                                                        <head>
                                                                                                                                                                            <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
                                                                                                                                                                                <style>
                                                                                                                                                                                        body { background: #0d1117; color: white; font-family: sans-serif; padding: 10px; }
                                                                                                                                                                                                .coin-box { background: #161b22; border: 1px solid #30363d; border-radius: 12px; padding: 15px; margin-bottom: 15px; }
                                                                                                                                                                                                        .price { color: #3fb950; font-size: 24px; font-weight: bold; }
                                                                                                                                                                                                                button { background: #21262d; color: white; border: 1px solid #30363d; padding: 5px; border-radius: 4px; font-size: 11px; cursor: pointer; margin-right: 3px;}
                                                                                                                                                                                                                    </style>
                                                                                                                                                                                                                    </head>
                                                                                                                                                                                                                    <body>
                                                                                                                                                                                                                        <h3 style="color:#58a6ff">🛰️ MAG LIVE: SISTEMAS UNEFA</h3>
                                                                                                                                                                                                                            {% for m in monedas %}
                                                                                                                                                                                                                                {% set m_id = m.replace('/', '_') %}
                                                                                                                                                                                                                                    <div class="coin-box">
                                                                                                                                                                                                                                            <b>{{ m }}</b>
                                                                                                                                                                                                                                                    <div id="price-{{ m_id }}" class="price">--.--</div>
                                                                                                                                                                                                                                                            <div style="font-size: 0.8em; margin: 5px 0;">🤖 IA: <span id="ia-{{ m_id }}" style="color:#58a6ff">Analizando...</span></div>
                                                                                                                                                                                                                                                                    <div class="btns">
                                                                                                                                                                                                                                                                                <button onclick="getHistory('{{ m }}', '{{ m_id }}', '1m', 60)">1H</button>
                                                                                                                                                                                                                                                                                            <button onclick="getHistory('{{ m }}', '{{ m_id }}', '1h', 24)">24H</button>
                                                                                                                                                                                                                                                                                                        <button onclick="getHistory('{{ m }}', '{{ m_id }}', '1d', 30)">1M</button>
                                                                                                                                                                                                                                                                                                                    <button onclick="getHistory('{{ m }}', '{{ m_id }}', '1w', 52)">1A</button>
                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                    <canvas id="chart-{{ m_id }}" height="110"></canvas>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                            {% endfor %}
                                                                                                                                                                                                                                                                                                                                                <script>
                                                                                                                                                                                                                                                                                                                                                        let charts = {};
                                                                                                                                                                                                                                                                                                                                                                async function getHistory(coin, id, tf='1h', limit=24) {
                                                                                                                                                                                                                                                                                                                                                                            const r = await fetch(`/api/historico?s=${coin}&t=${tf}&l=${limit}`);
                                                                                                                                                                                                                                                                                                                                                                                        const data = await r.json();
                                                                                                                                                                                                                                                                                                                                                                                                    if(charts[id]) charts[id].destroy();
                                                                                                                                                                                                                                                                                                                                                                                                                charts[id] = new Chart(document.getElementById('chart-'+id), {
                                                                                                                                                                                                                                                                                                                                                                                                                                type: 'line', data: { labels: data.tiempos, datasets: [{ data: data.precios, borderColor: '#58a6ff', pointRadius: 0, fill: true }] },
                                                                                                                                                                                                                                                                                                                                                                                                                                                options: { animation: false, plugins: { legend: { display: false } }, scales: { x: { display: false } } }
                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            async function update() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const r = await fetch('/api/data_update');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const data = await r.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for (const [m, p] of Object.entries(data.precios)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                let m_id = m.replace('/', '_');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('price-'+m_id).innerText = '$' + p.toLocaleString();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                document.getElementById('ia-'+m_id).innerText = data.ia[m];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            window.onload = () => { update(); setInterval(update, 10000); {% for m in monedas %} getHistory('{{ m }}', '{{ m.replace("/", "_") }}'); {% endfor %} };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </script>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '''

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # --- RUTAS CORREGIDAS ---
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.route('/')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def home():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if 'user' not in session: 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return redirect('/login_page')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return render_template_string(DASH_HTML, monedas=MONEDAS)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.route('/login_page')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def login_page(): 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return render_template_string(LOGIN_HTML)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @app.route('/login', methods=['POST'])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def login():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        u, p = request.form['u'], request.form['p']
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn = sqlite3.connect('usuarios.db')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                user = conn.execute("SELECT * FROM users WHERE username=? AND password=?", (u, p)).fetchone()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not user:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            conn.execute("INSERT INTO users (username, password) VALUES (?, ?)", (u, p))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    conn.commit()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        conn.close()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            session['user'] = u
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return redirect('/')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                @app.route('/api/data_update')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def data_update():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    precios = {m: exchange.fetch_ticker(m)['last'] for m in MONEDAS}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return jsonify({"precios": precios, "ia": analizar_inversion()})

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @app.route('/api/historico')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def api_historico():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            s, t, l = request.args.get('s'), request.args.get('t'), int(request.args.get('l'))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ohlcv = exchange.fetch_ohlcv(s, timeframe=t, limit=l)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return jsonify({"precios": [x[4] for x in ohlcv], "tiempos": [datetime.fromtimestamp(x[0]/1000).strftime('%d/%m') for x in ohlcv]})

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        init_db()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            port = int(os.environ.get('PORT', 5000))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                app.run(host='0.0.0.0', port=port)